name = "kubebuilder-zh-docs"
compatibility_date = "2024-01-01"

[env.production]
name = "kubebuilder-zh-docs"

[[pages_builds]]
destination = "book/book"
build_command = "./book/install-and-build.sh build"
build_watch_dirs = ["book/src", "book"]
